### PR TITLE
Added DELTA_RADIUS for LINEAR_PLUS

### PR DESCRIPTION
**Pull request by Velociraptor85**
Added DELTA_RADIUS for LINEAR_PLUS so it does not crash the head into the plate when calibrating the first time

### CODE REVIEW

**Review by emilio1625 — APPROVED** [review]

**Comment by emilio1625** [comment]
Thanks, i didn't  know for sure the delta radius for the linear plus, i don't have one, just one question before the merge, is this value the default from anycubic or is this only for your setup? I mean, do you think this value will be ok for most of the user?

**Comment by Velociraptor85** [comment]
Hej so that is the value I had in my head from my plus but I can recheck what I have and change accordingly If you want to have the value from the paper I could calculate that too But I think we could even enter a little bigger value so that it make a bowl shape and than the initial calibration would change this value to the correrct one for the user

**Comment by Velociraptor85** [comment]
Also for understanding the value I found this picture very helpfull [PIC](https://i1.ytimg.com/vi/Nexaf7XOoPg/maxresdefault.jpg)

**Comment by emilio1625** [comment]
If that value fixed the problem, then is good enough for my

**Pull request merged**
